services:
  postgres:
    image: postgres:16-alpine
    container_name: smartstudy-db
    environment:
      POSTGRES_DB: smartstudy
      POSTGRES_USER: smartstudy
      POSTGRES_PASSWORD: smartstudy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartstudy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
